### ISSUE TITLE
ImportError: cannot import name 'Self' from 'typing'

### ISSUE THREAD

**Issue by ghost** [penggrin12/stupidwalletapi#13]
Traceback (most recent call last):
  File "C:\Users\duh\Desktop\stupedsiteapi.py", line 2, in <module>
    import stupidwalletapi
  File "C:\Users\duh\AppData\Local\Programs\Python\Python39\lib\site-packages\stupidwalletapi\__init__.py", line 1, in <module>
    from .api import StupidWalletAPI
  File "C:\Users\duhs\AppData\Local\Programs\Python\Python39\lib\site-packages\stupidwalletapi\api.py", line 3, in <module>
    from .models import Cheque, Invoice
  File "C:\Users\duhs\AppData\Local\Programs\Python\Python39\lib\site-packages\stupidwalletapi\models.py", line 1, in <module>
    from typing import Optional, Self, List, Union
ImportError: cannot import name 'Self' from 'typing' (C:\Users\duh\AppData\Local\Programs\Python\Python39\lib\typing.py)

не хочет нифига импортировать

**Comment by Nefrit9087** [comment]
Привет. Платформа?

**Comment by Nefrit9087** [comment]
**Try these options:**

_Install WSL (Ubuntu) and install there by `sudo apt install python3 python-pip  && pip install stupidwalletapi --break-system-packages --user`_

Or the command: `python -m pip install stupidwalletapi`

**Comment by penggrin12** [comment]
пайтон обнови до 3.11
